# These are supported funding model platforms

github: [NjabuloJf]
patreon: ➥ sir Njabulo Jbメ
open_collective: AI
ko_fi: fana
tidelift: Njabulo Jb 
community_bridge: Njabulo Jb AI 
liberapay: Jb
issuehunt: happiness 
otechie: moment 
custom: ["https://njabulobot.vercel.app/"]
